### ISSUE TITLE
Add differentiatied search for big cities

### ISSUE THREAD

**Issue by JJ** [JJ/github-city-rankings#11]
Cities with more than 1k users will need two API searches: >0 followers and 0 followers.

**Comment by iblancasa** [comment]
Yesterday you say: "GitHub API returns me only 1k users"... What about parse HTML in big cities?

For example: Madrid
https://github.com/search?l=&p=2&q=location%3Amadrid&ref=advsearch&type=Users

Param p is the number of the page... We can iterate the pages and extract the profile URL of each user. When we receive a header with 404 error, we stop. Each user is defined between a div with "user-list-item" class.

I think it will be slower than using the API but... we will have all the users.

In addition, we can define "big city" like a city wich has 1k user o more (now a big city is defined in his json, true?).

**Comment by JJ** [comment]
10 by 10, it's 400 requests... and an entirely new API.

I'm not sure it returns more than 100 pages, either.

**Comment by iblancasa** [comment]
True.. it not returns more than 100 pages.. :weary:

**Comment by iblancasa** [comment]
Ok, ok... I have a new idea: when we had the last user in the 100 page, we save the number of followers and we can search users in this location with less of this number of followers...
It will be a lot of request but I think could be possible

**Comment by JJ** [comment]
That's what I do now: check out the get-cutoff.pl program. Then I set
cutoffs to the number of followers needed. The problem with some searches
is that they have more than 1K users; for instance, Madrid or BCN with 0
followers. Then I have to slice even more, by number of repos... it's hard
work, but I'll have to do it eventually.

**Comment by iblancasa** [comment]
I haven't see it :+1:

**Comment by JJ** [comment]
Check it out:
https://github.com/JJ/github-city-rankings/blob/master/get-cutoff.pl
