### ISSUE TITLE
How can I generate the alt-Andalucia ranking?

### ISSUE THREAD

**Issue by pleonex** [JJ/github-city-rankings#20]
I am trying to generate the alternative Andalucia ranking. I have seen that it should be a mix of using _get-AND.coffee_ (btw, the name is confusing, it seems it's the logical operation `&`) and _merge-json-files.coffee_. Specially, I don't know very well how to execute the latter, what is the second argument?

Maybe we could combine both in a single script or at least add how to do it in the README.

**Comment by JJ** [comment]
No, that does not work, sorry. Run this
```
./merge-json-files.coffee Andalucía "@(Andalucía|Granada|Jaén|Málaga|Almería|Córdoba|Cádiz|Sevilla|Huelva)"
```
