### ISSUE TITLE
Start batch and get result in top

### ISSUE THREAD

**Issue by iblancasa** [JJ/github-city-rankings#22]
I want to start a job in [utils-node.js](https://github.com/JJ/github-city-rankings/blob/master/lib/utils-node.js). I need to get the return value (in [top.coffee](https://github.com/JJ/github-city-rankings/blob/master/lib/top.coffee)) when this new job finish.

How can I do it?
Thanks in advance

**Comment by JJ** [comment]
There's a complicated chain of callbacks involved. What do you want to do
exactly?

**Comment by iblancasa** [comment]
I want to load data from another JSON and insert the return value in markdown layout.
I am thinking about blocking execution and wait response from server...

**Comment by iblancasa** [comment]
It is not a good idea.

Could I create a new var in "utils-node.js" (with exports.VAR=..... ),  modify it and query it from top.coffee?

**Comment by iblancasa** [comment]
Ok, I solve it. When all data was calculated (in my function) I put ``exports.myvar=value``. In top.coffe, I referenced it using ``node_utils.myvar``

**Comment by JJ** [comment]
Great. Closing?

**Comment by iblancasa** [comment]
Yes :D 
Thanks
