### ISSUE TITLE
Hacer opcional la recuperación del dato anterior

### ISSUE THREAD

**Issue by JJ** [JJ/github-city-rankings#25]
Porque eh `./check_all.sh` compruebo si hay o no suficientes páginas bajadas, porejemplo. Y además, porqeu ahora da un error:
```
/home/jmerelo/Code/top-github/github-city-rankings/lib/utils-node.js:107
                             throw [response2.error,response2.text].join("\n")
                                                                    ^
Error: got 400 response
<!DOCTYPE html>
<!--

Hello future GitHubber! I bet you're here to remove those nasty inline styles,
DRY up these templates and make 'em nice and re-usable, right?

Please, don't. https://github.com/styleguide/templates/2.0

-->
Míralo, por favor, @iblancacasa

**Comment by iblancasa** [comment]
¿Este error da siempre o solo con algunas ciudades?

Lo miro en cuanto pueda, que me pillas viajando

**Comment by JJ** [comment]
Lo da siempre. Al final lo he puesto optativo, el problema es que para que
lo use tendrá que modificarse todos y cada uno de los ficheros de
configuración... No sé muy bien qué hacer. Habría que reestructurarlo casi
todo. Quizás otra forma sería simplemente no lanzar una excepción cuando no
encuentre el fichero.

2015-08-16 13:09 GMT+02:00 Israel Blancas <notifications@github.com>:

> ¿Este error da siempre o solo con algunas ciudades?
>
> Lo miro en cuanto pueda, que me pillas viajando
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/github-city-rankings/issues/25#issuecomment-131525332>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
Falta alguna cabecera. Tiene que ser eso por que, en la línea que se imprime justo antes de la traza que has puesto, pone la URL a la que se está haciendo la petición. Si pones esa URL en el navegador, no hay error alguno...

En la función getLast hay dos peticiones al servidor (una está en el callback de la otra), no creo que sea problema de usar el mismo objeto request en el callback, ¿no?

Otra cosa que se me ocurre, y que es la que me parece que es la hipótesis más fuerte... es que está haciendo peticiones HTTP a una dirección HTTPS (de hecho llevo un rato haciendo peticiones desde el terminal y no consigo que me devuelva una respuesta 200, pero, si entro por el navegador, no hay problema).

**Comment by iblancasa** [comment]
Ni caso a lo último... debe ser alguna cabecera

**Comment by JJ** [comment]
Lo que he visto por ahí es que es problema de redirección + certificado.
Tampoco estoy seguro de que sea la mejor forma de hacer las cosas. El
script de todas formas deposita el resultado en otro fichero local. De
hecho, ni siquiera habría que mirar los commits: bastaría con mirar el
estado del fichero local, si existe...

**Comment by iblancasa** [comment]
Psé. Es verdad. Realmente lo último que hay online es la versión que hay colgada en Github. Sería necesario comparar con esa versión. Lo que podríamos hacer es bajar la última versión que hay del fichero.

Me he dado cuenta que cuando falla al responder al CURL es cuando se está intentando obtener un fichero antiguo,es decir, de un commit anterior (y si éste es JSON, por que en varios scripts no he tenido problema). Podríamos coger simplemente esa versión y descargarla para comparar... o lo que dices, comparar con el ya descargado (aunque a eso le veo que si no se tiene la última versión decargada...) Pero bueno, uno u otro es más que viable.

Como quieras y lo vamos viendo. Estoy camino de Madrid, supongo que por las noches estaré online y podemos ir haciendo

**Comment by JJ** [comment]
Bueno, no es descargado. Es que los tengo en otro directorio. El directorio
de salida se puede leer del propio fichero de configuración.

**Comment by iblancasa** [comment]
Sí, está en otro directorio, que es después el repositorio en el que están los datos ¿no? De hecho, al ejecutar el ranking para una ciudad, si no está esa carpeta (creo recordar que solo es la carpeta) salta una excepción y se detiene la ejecución

**Comment by JJ** [comment]
Justo.

El 16 de agosto de 2015, 18:56, Israel Blancas <notifications@github.com>
escribió:

> Sí, está en otro directorio, que es después el repositorio en el que están
> los datos ¿no? De hecho, al ejecutar el ranking para una ciudad, si no está
> esa carpeta (creo recordar que solo es la carpeta) salta una excepción y se
> detiene la ejecución
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/github-city-rankings/issues/25#issuecomment-131581887>
> .
>



-- 
JJ
