### ISSUE TITLE
Bad img path on alt-Spain ranking

### ISSUE THREAD

**Issue by JuanjoSalvador** [JJ/github-city-rankings#33]
In the alt-Spain ranking, where should be `up.gif`, `equal.gif`or `down.gif`, there is no image loaded. If I inspect the path, I get this:

```
https://raw.githubusercontent.com/JJ/github-city-rankings/master/img/.gif
```

Probably, filename is not generated correctly.

**Comment by JJ** [comment]
Probably, but I'm not updating this any more... feel free to fix it.

**Comment by JuanjoSalvador** [comment]
I'm looking for the error. I think I found it... Pull request incoming

**Comment by JJ** [comment]
Thanks!

2016-06-09 13:26 GMT+02:00 Juan José Salvador <notifications@github.com>:

> I'm looking for the error. I think I found it... Pull request incoming
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/JJ/github-city-rankings/issues/33#issuecomment-224868051>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAB9ANXvTUwkTDWoUKsddTKGvtYiBTDks5qJ_hSgaJpZM4Ix3ly>
> .
>



-- 
JJ

**Comment by JuanjoSalvador** [comment]
You're welcome :D
