### ISSUE TITLE
Default user image size

### ISSUE THREAD

**Issue by pleonex** [JJ/github-city-rankings#6]
There is a problem resizing auto-created profile images. It seems that the Github server does not support the 's' query for that kind of images, ie:
`https://avatars4.githubusercontent.com/u/6162733?v=3&s=64` returns a 420x420 image
![DefaultImage](https://avatars4.githubusercontent.com/u/6162733?v=3&s=64)
but `https://avatars0.githubusercontent.com/u/3107481?v=3&s=64` returns a 64x64 image
![Image](https://avatars0.githubusercontent.com/u/3107481?v=3&s=64)

Since it's hard to check whether it's a default image or not (we could just not display them), a solution could be to use an external API like [Embedly](http://embed.ly/)

![ResizeImage](http://i.embed.ly/1/display/resize?url=https%3A%2F%2Favatars4.githubusercontent.com%2Fu%2F6162733&grow=true&key=5ddbd4a9e42542ca9e57172ffc03e2c5&height=64&width=64)
`http://i.embed.ly/1/display/resize?url=https%3A%2F%2Favatars4.githubusercontent.com%2Fu%2F6162733&grow=true&key=5ddbd4a9e42542ca9e57172ffc03e2c5&height=64&width=64`

**Comment by JJ** [comment]
Great idea!

2015-01-12 15:40 GMT+01:00 Benito Palacios <notifications@github.com>:

> There is a problem resizing auto-created profile images. It seems that the
> Github server does not support the 's' query for that kind of images, ie:
> https://avatars4.githubusercontent.com/u/6162733?v=3&s=64 returns a
> 420x420 image
> [image: DefaultImage]
> <https://avatars4.githubusercontent.com/u/6162733?v=3&s=64>
> but https://avatars0.githubusercontent.com/u/3107481?v=3&s=64 returns a
> 64x64 image
> [image: Image] <https://avatars0.githubusercontent.com/u/3107481?v=3&s=64>
>
> Since it's hard to check whether it's a default image or not (we could
> just not display them), a solution could be to use an external API like
> Embedly <http://embed.ly/>
>
> [image: ResizeImage]
> <https://camo.githubusercontent.com/10378a99c86753fd023f8ea49b67448a6a24f546/687474703a2f2f692e656d6265642e6c792f312f646973706c61792f726573697a653f75726c3d687474707325334125324625324661766174617273342e67697468756275736572636f6e74656e742e636f6d25324675253246363136323733332667726f773d74727565266b65793d3564646264346139653432353432636139653537313732666663303365326335266865696768743d36342677696474683d3634>
>
> http://i.embed.ly/1/display/resize?url=https%3A%2F%2Favatars4.githubusercontent.com%2Fu%2F6162733&grow=true&key=5ddbd4a9e42542ca9e57172ffc03e2c5&height=64&width=64
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/github-city-rankings/issues/6>.
>



-- 
JJ
